name: Java CI

on: [ push ]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hi Zahra"
      - name: show java version
        run: java -version
      - name: Error step
        run: test error message
